// Copyright 2026 Muvon Un Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Compression anchor — persistent structured memory across compactions.
//!
//! The anchor is what survives every plan/conversation compaction in a
//! session. Instead of regenerating a summary from scratch each time the
//! window fills (the previous behavior), each compaction produces an
//! `AnchorUpdate` describing only what was new in the dropped span and
//! merges it into the existing `Anchor`. This preserves technical details
//! (file paths, error messages, decisions) across many compaction cycles.
//!
//! Reference: Factory.ai's "anchored iterative summarization" — measured
//! to retain technical detail more reliably than regenerate-each-pass.
//!
//! This module defines the data model and merge logic. Compaction wiring
//! lives in `src/mcp/core/plan/compression.rs` and the conversation
//! compression module — see those for how `extend()` is called.

use serde::{Deserialize, Serialize};

/// Persistent compaction anchor. Lives on `SessionInfo` and is updated on
/// every successful compaction. Empty-by-default — sessions that never
/// compact carry an empty anchor that costs nothing to serialize.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct Anchor {
	/// One-paragraph statement of what the session is trying to accomplish.
	/// Set on the first compaction, refined on subsequent ones.
	#[serde(default, skip_serializing_if = "String::is_empty")]
	pub intent: String,

	/// Concrete changes made (files modified, commands run, side effects).
	/// Append-only; deduplicated on insert.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub changes_made: Vec<String>,

	/// Decisions reached and why. Survives indefinitely — the model needs
	/// these to stay coherent across long sessions.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub decisions: Vec<String>,

	/// Files touched or read with content the model still needs to know
	/// about. Path strings, deduplicated.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub file_refs: Vec<String>,

	/// Errors / failures encountered and how they were resolved (or not).
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub errors_seen: Vec<String>,

	/// What the session intended to do next at the time of compaction.
	/// Always overwritten by the latest update — older next-steps are
	/// stale by definition.
	#[serde(default, skip_serializing_if = "Vec::is_empty")]
	pub next_steps: Vec<String>,

	/// Signature of the user request `intent` was resolved from, so a later turn
	/// can tell whether that goal is still the live one. `intent` is refreshed
	/// only by `extend()`, i.e. on compaction — but the user can issue a new
	/// request at any time, and a resumed session typically does so on a freshly
	/// compacted (small) context that will not compact again for many turns.
	/// Without this, `recite_note` keeps injecting the previous request as
	/// "Goal (fixed)" and the model rules the new request out of scope.
	/// 0 = unknown (legacy sessions), which recites exactly as before.
	#[serde(default, skip_serializing_if = "is_zero_u64")]
	pub intent_task_sig: u64,

	/// Number of compactions that have folded into this anchor.
	#[serde(default, skip_serializing_if = "is_zero")]
	pub compactions_folded: u32,

	/// Unix timestamp of the most recent compaction merged into this anchor.
	#[serde(default, skip_serializing_if = "is_zero_u64")]
	pub last_compacted_at: u64,
}

fn is_zero(n: &u32) -> bool {
	*n == 0
}
fn is_zero_u64(n: &u64) -> bool {
	*n == 0
}

/// Delta produced by a single compaction. Generated by an LLM
/// summarizing the dropped span; merged into `Anchor` via `extend`.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct AnchorUpdate {
	#[serde(default)]
	pub intent: Option<String>,
	#[serde(default)]
	pub changes_made: Vec<String>,
	#[serde(default)]
	pub decisions: Vec<String>,
	#[serde(default)]
	pub file_refs: Vec<String>,
	#[serde(default)]
	pub errors_seen: Vec<String>,
	#[serde(default)]
	pub next_steps: Vec<String>,
	/// Signature of the user request `intent` was resolved from. `None` leaves
	/// the anchor's existing signature untouched.
	#[serde(default)]
	pub intent_task_sig: Option<u64>,
}

/// Stable signature of a user request, used to tell "still the same ask" from
/// "the user has moved on". Deliberately not `DefaultHasher`: anchors are
/// serialized and re-read by a later process, so the function must not change
/// with the toolchain. FNV-1a over the trimmed bytes; collisions only cost a
/// suppressed recitation.
pub fn task_sig(task: &str) -> u64 {
	let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
	for byte in task.trim().as_bytes() {
		hash ^= u64::from(*byte);
		hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
	}
	// 0 is reserved for "unknown".
	if hash == 0 {
		1
	} else {
		hash
	}
}

impl Anchor {
	/// Whether the anchor has any content. Used to decide between
	/// "first compaction" and "extend existing" formatting.
	pub fn is_empty(&self) -> bool {
		self.intent.is_empty()
			&& self.changes_made.is_empty()
			&& self.decisions.is_empty()
			&& self.file_refs.is_empty()
			&& self.errors_seen.is_empty()
			&& self.next_steps.is_empty()
	}

	/// Merge an update into this anchor. Append-only fields (`changes_made`,
	/// `decisions`, `file_refs`, `errors_seen`) are deduplicated on insert.
	/// `intent` replaces whenever the update supplies one. Suppliers deliberately
	/// do NOT guard with `is_empty()`: a first-write-wins intent froze the goal at
	/// whatever the session opened with, and `recite::recite_note` re-injects it
	/// mid-turn as "Goal (fixed)" — so the supervisor kept steering the model back
	/// to work the user had already moved past. Both suppliers now re-resolve the
	/// CURRENT request every time (conversation compaction from its fidelity goal,
	/// task compaction from the latest real user turn) and skip the update when
	/// that resolves empty, so the previous value survives rather than being
	/// cleared. `next_steps` always replaces.
	pub fn extend(&mut self, update: AnchorUpdate, now_unix: u64) {
		if let Some(intent) = update.intent {
			let trimmed = intent.trim();
			if !trimmed.is_empty() {
				self.intent = trimmed.to_string();
				// Track which request this goal came from; suppliers resolve the
				// live user turn, so a later turn can detect it has moved on.
				self.intent_task_sig = update.intent_task_sig.unwrap_or(0);
			}
		}

		extend_dedup(&mut self.changes_made, update.changes_made);
		extend_dedup(&mut self.decisions, update.decisions);
		extend_dedup(&mut self.file_refs, update.file_refs);
		extend_dedup(&mut self.errors_seen, update.errors_seen);

		// Latest next-steps win; older "what we plan to do" lines go stale.
		if !update.next_steps.is_empty() {
			self.next_steps = update.next_steps;
		}

		self.compactions_folded = self.compactions_folded.saturating_add(1);
		self.last_compacted_at = now_unix;
	}

	/// Render the anchor as a compact XML block suitable for inclusion in
	/// compressed-knowledge messages. XML over markdown: subsequent
	/// compressions re-feed this body as transcript input, and Claude is
	/// tuned to parse XML-delimited sections more reliably than markdown
	/// headers across paraphrase cycles.
	pub fn to_xml(&self) -> String {
		let mut out = String::with_capacity(512);
		if !self.intent.is_empty() {
			out.push_str("<intent>");
			out.push_str(self.intent.trim());
			out.push_str("</intent>\n");
		}
		render_list(&mut out, "decisions", "decision", &self.decisions);
		render_list(&mut out, "changes_made", "change", &self.changes_made);
		render_list(&mut out, "errors_seen", "entry", &self.errors_seen);
		render_list(&mut out, "file_references", "file", &self.file_refs);
		render_list(&mut out, "next_steps", "step", &self.next_steps);
		if self.compactions_folded > 0 {
			out.push_str(&format!("<folds>{}</folds>\n", self.compactions_folded));
		}
		out
	}
}

fn extend_dedup(target: &mut Vec<String>, additions: Vec<String>) {
	for item in additions {
		let trimmed = item.trim();
		if trimmed.is_empty() {
			continue;
		}
		if !target.iter().any(|existing| existing == trimmed) {
			target.push(trimmed.to_string());
		}
	}
}

fn render_list(out: &mut String, outer: &str, item: &str, items: &[String]) {
	let non_empty: Vec<&String> = items.iter().filter(|s| !s.trim().is_empty()).collect();
	if non_empty.is_empty() {
		return;
	}
	out.push_str(&format!("<{outer}>\n"));
	for v in non_empty {
		out.push_str(&format!("<{item}>{}</{item}>\n", v.trim(), item = item));
	}
	out.push_str(&format!("</{outer}>\n"));
}

#[cfg(test)]
#[path = "anchor_tests.rs"]
mod tests;
